name: Check Markdown links

on:
  pull_request:
    paths:
      - "**/*.md"
      - "markdown_link_check_config.json"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
      - name: Install markdown-link-check
        run: npm i -g markdown-link-check@3.11.0
      - name: Run markdown-link-check on MD files
        run: find . -name "*.md" | xargs -n 1 markdown-link-check -c markdown_link_check_config.json -q
